import { Lead } from '../models/Lead'
import { emitToTeam } from '../config/socket'
import { WebsiteLeadPayload } from '../types/webhook.types'
import { logger } from '../utils/logger'
import { notifyNewLeadCreated } from '../services/notification.service'

const normalizePhone = (value: string): string => value.replace(/\D/g, '')

// ── Deduplication guard ──────────────────────────────────────────────────────
// Prevents duplicate leads when multiple webhook sources fire for the same
// form submission (e.g. Elementor's native webhook + custom JS fetch both
// posting to the same endpoint within milliseconds of each other).
//
// Key  : last-10-digit normalized phone number
// Value: timestamp of the first processed request
//
// Any second request for the same phone that arrives within DEDUP_WINDOW_MS
// is silently absorbed — it will NOT create a new lead.
const recentlyProcessed = new Map<string, number>()
const DEDUP_WINDOW_MS = 12_000 // 12 seconds

// Periodic cleanup so the map doesn't grow forever on long-running processes
setInterval(() => {
  const cutoff = Date.now() - DEDUP_WINDOW_MS
  for (const [phone, ts] of recentlyProcessed) {
    if (ts < cutoff) recentlyProcessed.delete(phone)
  }
}, 60_000)
// ────────────────────────────────────────────────────────────────────────────

const isAutoGeneratedLeadName = (name?: string | null, phone?: string | null): boolean => {
  const trimmedName = String(name || '').trim()
  if (!trimmedName) return true

  const normalizedLeadPhone = normalizePhone(String(phone || ''))

  if (/^Direct(?:\s+Lead|\s+\d{4})$/i.test(trimmedName)) return true
  if (/^Manual(?:\s+Lead|\s+\d{4})$/i.test(trimmedName)) return true
  if (/^Lead\s+\d{4}$/i.test(trimmedName)) return true
  if (/^Exotel\s+\d{4}$/i.test(trimmedName)) return true
  if (normalizedLeadPhone && normalizePhone(trimmedName) === normalizedLeadPhone) return true

  return false
}

export const processWebsiteLead = async (payload: WebsiteLeadPayload): Promise<void> => {
  try {
    const { name, phone, email, city, campaign, budget, message, utmSource, utmMedium, utmCampaign, utmTerm, utmContent, gclid, rawFields } = payload

    const submittedName = String(name || '').trim()
    const normalizedPhone = normalizePhone(phone)
    const phoneKey = normalizedPhone.slice(-10)

    // ── Dedup check ──────────────────────────────────────────────────────────
    // If we already processed a submission from this phone within the last
    // 12 seconds, discard this request — it is a duplicate fire from a second
    // webhook source (e.g. Elementor + custom JS on the same form).
    const lastProcessedAt = recentlyProcessed.get(phoneKey)
    if (lastProcessedAt && Date.now() - lastProcessedAt < DEDUP_WINDOW_MS) {
      logger.info('Website lead duplicate suppressed by dedup guard', { phone: phoneKey })
      return
    }
    // Claim this phone key immediately before any await so concurrent requests
    // that arrive within the same event loop tick are also blocked.
    recentlyProcessed.set(phoneKey, Date.now())
    // ─────────────────────────────────────────────────────────────────────────

    const existingLead =
      (campaign ? await Lead.findOne({ campaign: campaign, phone }).exec() : null) ||
      (normalizedPhone
        ? await Lead.findOne({ phone: { $regex: `${normalizedPhone.slice(-10)}$` } }).exec()
        : null)

    // If the lead ALREADY exists, the webhook is re-firing for a lead the rep
    // may have manually curated in the CRM. We MUST NOT touch business fields
    // (source, disposition, name, city, owner, isInQueue, etc.) — doing so
    // would stomp the rep's work. Only record the new submission activity.
    if (existingLead) {
      const updateOnExisting: Record<string, unknown> = { lastActivity: new Date() }
      // Merge fresh form fields into websiteFormData so the latest submission
      // is still captured for reference, but never lose the original keys.
      if (rawFields && Object.keys(rawFields).length > 0) {
        updateOnExisting.websiteFormData = {
          ...(existingLead.websiteFormData || {}),
          ...rawFields,
        }
      }
      await Lead.updateOne({ _id: existingLead._id }, { $set: updateOnExisting })

      emitToTeam('all', 'lead:incoming', {
        lead: {
          id: existingLead._id,
          name: existingLead.name,
          phone: existingLead.phone,
          city: existingLead.city,
          source: existingLead.source,
          owner: existingLead.owner || null,
        },
      })

      logger.info('Website webhook — lead already exists, only lastActivity bumped', {
        leadId: String(existingLead._id),
      })
      return
    }

    // Truly new lead — create fresh.
    const lead = await Lead.create({
      name,
      phone,
      email: email || null,
      city: city || 'Unknown',
      source: 'Website',
      disposition: 'New',
      campaign: campaign || null,
      budget: budget || null,
      lastActivityNote: message || null,
      utmSource: utmSource || null,
      utmMedium: utmMedium || null,
      utmCampaign: utmCampaign || null,
      utmTerm: utmTerm || null,
      utmContent: utmContent || null,
      googleClickId: gclid || null,
      lastActivity: new Date(),
      websiteFormData: rawFields || null,
      isInQueue: false,
    })

    if (submittedName && isAutoGeneratedLeadName(lead.name, lead.phone || phone)) {
      lead.name = submittedName
      await lead.save()
    }

    emitToTeam('all', 'lead:incoming', {
      lead: { id: lead._id, name: lead.name, phone: lead.phone, city: lead.city, source: 'Website', owner: lead.owner || null },
    })

    // existingLead path returned above, so this is guaranteed a new lead.
    void notifyNewLeadCreated(lead).catch(() => null)

    logger.info('Website lead created', { leadId: lead._id })
  } catch (err) {
    // Remove from dedup map on failure so a genuine retry is not suppressed
    const phoneKey = normalizePhone(payload.phone).slice(-10)
    recentlyProcessed.delete(phoneKey)
    logger.error('processWebsiteLead error', err)
    throw err
  }
}
