import { Lead } from '../models/Lead'
import { emitToTeam } from '../config/socket'
import { WebsiteLeadPayload } from '../types/webhook.types'
import { logger } from '../utils/logger'
import { notifyNewLeadCreated } from '../services/notification.service'

const normalizePhone = (value: string): string => value.replace(/\D/g, '')

// ── Deduplication guard ──────────────────────────────────────────────────────
// Prevents duplicate leads when multiple webhook sources fire for the same
// form submission (e.g. Elementor's native webhook + custom JS fetch both
// posting to the same endpoint within milliseconds of each other).
//
// Key  : last-10-digit normalized phone number
// Value: timestamp of the first processed request
//
// Any second request for the same phone that arrives within DEDUP_WINDOW_MS
// is silently absorbed — it will NOT create a new lead.
const recentlyProcessed = new Map<string, number>()
const DEDUP_WINDOW_MS = 12_000 // 12 seconds

// Periodic cleanup so the map doesn't grow forever on long-running processes
setInterval(() => {
  const cutoff = Date.now() - DEDUP_WINDOW_MS
  for (const [phone, ts] of recentlyProcessed) {
    if (ts < cutoff) recentlyProcessed.delete(phone)
  }
}, 60_000)
// ────────────────────────────────────────────────────────────────────────────

const isAutoGeneratedLeadName = (name?: string | null, phone?: string | null): boolean => {
  const trimmedName = String(name || '').trim()
  if (!trimmedName) return true

  const normalizedLeadPhone = normalizePhone(String(phone || ''))

  if (/^Direct(?:\s+Lead|\s+\d{4})$/i.test(trimmedName)) return true
  if (/^Manual(?:\s+Lead|\s+\d{4})$/i.test(trimmedName)) return true
  if (/^Lead\s+\d{4}$/i.test(trimmedName)) return true
  if (/^Exotel\s+\d{4}$/i.test(trimmedName)) return true
  if (normalizedLeadPhone && normalizePhone(trimmedName) === normalizedLeadPhone) return true

  return false
}

export const processWebsiteLead = async (payload: WebsiteLeadPayload): Promise<void> => {
  try {
    const { name, phone, email, city, campaign, budget, message, utmSource, utmMedium, utmCampaign, utmTerm, utmContent, gclid, rawFields } = payload

    const submittedName = String(name || '').trim()
    const normalizedPhone = normalizePhone(phone)
    const phoneKey = normalizedPhone.slice(-10)

    // ── Dedup check ──────────────────────────────────────────────────────────
    // If we already processed a submission from this phone within the last
    // 12 seconds, discard this request — it is a duplicate fire from a second
    // webhook source (e.g. Elementor + custom JS on the same form).
    const lastProcessedAt = recentlyProcessed.get(phoneKey)
    if (lastProcessedAt && Date.now() - lastProcessedAt < DEDUP_WINDOW_MS) {
      logger.info('Website lead duplicate suppressed by dedup guard', { phone: phoneKey })
      return
    }
    // Claim this phone key immediately before any await so concurrent requests
    // that arrive within the same event loop tick are also blocked.
    recentlyProcessed.set(phoneKey, Date.now())
    // ─────────────────────────────────────────────────────────────────────────

    const existingLead =
      (campaign ? await Lead.findOne({ campaign: campaign, phone }).exec() : null) ||
      (normalizedPhone
        ? await Lead.findOne({ phone: { $regex: `${normalizedPhone.slice(-10)}$` } }).exec()
        : null)

    const lead =
      existingLead ||
      (await Lead.create({
        name,
        phone,
        email: email || null,
        city: city || 'Unknown',
        source: 'Website',
        disposition: 'New',
        campaign: campaign || null,
        budget: budget || null,
        lastActivityNote: message || null,
        utmSource: utmSource || null,
        utmMedium: utmMedium || null,
        utmCampaign: utmCampaign || null,
        utmTerm: utmTerm || null,
        utmContent: utmContent || null,
        googleClickId: gclid || null,
        lastActivity: new Date(),
        websiteFormData: rawFields || null,
      }))

    if (submittedName && isAutoGeneratedLeadName(lead.name, lead.phone || phone)) {
      lead.name = submittedName
    } else {
      lead.name = lead.name || submittedName
    }
    lead.phone = lead.phone || phone
    lead.email = lead.email || email || null
    lead.city = lead.city && lead.city !== 'Unknown' ? lead.city : city || 'Unknown'
    lead.source = 'Website'
    lead.campaign = campaign || lead.campaign || null
    lead.budget = budget || lead.budget || null
    lead.lastActivityNote = message || lead.lastActivityNote || null
    lead.utmSource = utmSource || lead.utmSource || null
    lead.utmMedium = utmMedium || lead.utmMedium || null
    lead.utmCampaign = utmCampaign || lead.utmCampaign || null
    lead.utmTerm = utmTerm || lead.utmTerm || null
    lead.utmContent = utmContent || lead.utmContent || null
    lead.googleClickId = gclid || lead.googleClickId || null
    lead.lastActivity = new Date()
    lead.isInQueue = false
    // Always overwrite websiteFormData with the latest submission so we
    // capture updated fields on re-submits from the same lead.
    if (rawFields && Object.keys(rawFields).length > 0) {
      lead.websiteFormData = rawFields
    }
    await lead.save()

    emitToTeam('all', 'lead:incoming', {
      lead: { id: lead._id, name: lead.name, phone: lead.phone, city: lead.city, source: 'Website', owner: lead.owner || null },
    })

    if (!existingLead) {
      void notifyNewLeadCreated(lead).catch(() => null)
    }

    logger.info('Website lead created', { leadId: lead._id })
  } catch (err) {
    // Remove from dedup map on failure so a genuine retry is not suppressed
    const phoneKey = normalizePhone(payload.phone).slice(-10)
    recentlyProcessed.delete(phoneKey)
    logger.error('processWebsiteLead error', err)
    throw err
  }
}
